
{{Useful Function}}
{{New items|3.0152|1.5.2|This useful function is no longer neeeded because it's already included in every script.|7596}}

Usually, errors that occur inside a coroutine do not get reported, which can lead to all sorts of coding catastrophes. To fix, include the following code before any use of coroutine.resume

==Code==
<code>
_coroutine_resume = coroutine.resume
function coroutine.resume(...)
	local state,result = _coroutine_resume(...)
	if not state then
		outputDebugString( tostring(result), 1 )	-- Output error message
	end
	return state,result
end
</syntaxhighlight>

==See Also==
{{Useful_Functions}}